version: '3'
services:
  bot-dev:
    image: python:3.7
    env_file: .env
    volumes:
      - .:/bot-app
    working_dir: /bot-app
    ports:
      - "5555:5555"
    environment:
      - FLASK_ENV=development
    entrypoint: /bin/bash
    tty: true
